# This workflow will run unit tests

name: Update skill.json
on:
  push:

jobs:
  update_skill_json:
    permissions:
      contents: write
    uses: neongeckocom/.github/.github/workflows/skill_update_json_spec.yml@master
